name: biriyani
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_native_splash: ^2.4.3
  flutter_animate: ^4.5.1
  lottie: ^3.1.3
  flutter_screenutil: ^5.9.3
  rounded_loading_button_plus: ^3.0.1
  flutter_vector_icons: ^2.0.0
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_native_splash:  
  color: "#C72C41"
  image: assets/images/splash_img.png

  android_12:
    image: assets/images/splash_img.png
    color: "#C72C41"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 
  
